spring.application.name=ms-administracion-archivos
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/7d6febd8-1893-4485-a002-1194f8dde63d/v2.0

# Configuracion para logs de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG


# Configuracion EFS
efs.path=/app/efs
