spring.application.name=ms-administracion-archivos
server.port=8080

# Configuracion para logs de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG


# Configuracion EFS
efs.path=/app/efs
